/**
 * 干员名称映射对象
 * 包含所有干员的中文名称及特殊格式定义
 */
const characterName = {
	ceshimrfz:"测试",

	acemrfz: "Ace",
	baocunzhemrfz: '保存者',
	yizumikemrfz: '伊祖米克',
	kelisitengmrfz: '克丽斯腾',
	shuangxingmrfz: '霜星',
	donghenshuangxingmrfz: '<font color=#8dc2f6><b>冬痕</b></font>霜星',
	aiguozhemrfz: '爱国者',
	doushitalulamrfz_prefix: {
		name:"斗士",
		color: "#FF1111",
		nature: "woodmm",
	},
	doushitalulamrfz: '斗士塔露拉',
	// aibulanamrfz: '爱布拉娜',
	teleixiyamrfz: '特蕾西娅',
	teleixisimrfz: '特雷西斯',
	shuangyemrfz: '霜叶',
	yueyuemrfz: '跃跃',
	lutuomrfz: '露托',
	shendianmrfz: '深靛',
	friston3mrfz: '弗里斯腾',
	talaidingzhenmrfz:'泰拉丁真',
	qiaojiakelifumrfz: '桥夹克里夫',
	puruisaisimrfz: '普瑞赛斯',
	ailinimrfz: "艾丽妮",
	hongxuemrfz: "鸿雪",
	xiaoyangmrfz: "艾雅法拉",
	yinhuimrfz: "银灰",
	lingzhimrfz: "灵知",
	liumingmrfz: "流明",
	chizuimrfz: "斥罪",
	niyanmrfz: "泥岩",
	chengshanmrfz: "澄闪",
	wmrfz: "W",
	spsikadimrfz: "浊心斯卡蒂",
	spsikadimrfz_prefix: "浊心",
	sikadimrfz: "斯卡蒂",
	spdegoumrfz: "缄默德克萨斯",
	spdegoumrfz_prefix: "缄默",
	maennamrfz: "玛恩纳",
	splinguangmrfz: "耀骑士临光",
	splinguangmrfz_prefix: "耀骑士",
	kaierximrfz: "凯尔希",
	shanmrfz: "山",
	geleidiyamrfz: "歌蕾蒂娅",
	chenmrfz: "陈",
	xingxiongmrfz: "星熊",
	kanielianmrfz: "卡涅利安",
	kuiyingmrfz: "傀影",
	mositimamrfz: "莫斯提马",
	keebomrfz: "刻俄柏",
	feiyameitamrfz: "菲亚梅塔",
	jicimrfz: "棘刺",
	yeyingmrfz: "夜莺",
	helagemrfz: "赫拉格",
	wendimrfz: "温蒂",
	senranmrfz: "森蚺",
	senrantieyumrfz:
		"<font color=`#FF1111`>" +
		[
			"浪人",
			"帝王",
			"强力",
			"离子",
			"军团",
			"烈焰",
			"先锋",
		].randomGet() +
		"</font>森蚺",
	ashmrfz: "ASH",
	kamimrfz: "异客",
	nianmrfz: "年",
	lingmrfz: "令",
	fengdimrfz: "风笛",
	qinliumrfz: "琴柳",
	laolimrfz: "老鲤",
	amrfz: "阿",
	heimrfz: "黑",
	chongyuemrfz: "重岳",
	anjielinamrfz: "安洁莉娜",
	haojiaomrfz: "号角",
	yanweimrfz: "焰尾",
	xigymrfz: "夕",
	nengtianshimrfz: "能天使",
	yuanyamrfz: "远牙",
	midiexiangmrfz: "迷迭香",
	spzzxpmrfz: "假日威龙陈",
	spzzxpmrfz_prefix: "假日威龙",
	shuiyuemrfz: "水月",
	qiubaimrfz: "仇白",
	spyoulingshamrfz: "归溟幽灵鲨",
	spyoulingshamrfz_prefix: "归溟",
	baitiemrfz: "白铁",
	weinamrfz: "推进之王",
	siyemrfz: "伺夜",
	spjiaweiermrfz: "百炼嘉维尔",
	spjiaweiermrfz_prefix: "百炼",
	semrfz: "史尔特尔",
	linmrfz: "林",
	duoluoximrfz: "多萝西",
	kongxianmrfz: "空弦",
	spyedaomrfz: "麒麟R夜刀",
	yineisimrfz: "伊内丝",
	miumiumrfz: "缪尔赛思",
	heijianmrfz: "黑键",
	yifulitemrfz: "伊芙利特",
	sphemomrfz: "淬羽赫默",
	sphemomrfz_prefix: "淬羽",
	saileiyamrfz: "塞雷娅",
	spweicaomrfz: "焰影苇草",
	spweicaomrfz_prefix: "焰影",
	huoerhaiyamrfz: "霍尔海雅",
	huangmrfz: "煌",
	linglanmrfz: "铃兰",
	shanlingmrfz: "闪灵",
	maizhelunmrfz: "麦哲伦",
	cuoemrfz: "嵯峨",
	palasimrfz: "帕拉斯",
	xiaguangmrfz: "瑕光",
	zaolumrfz: "早露",
	spshihuaiyamrfz: "琳琅诗怀雅",
	spshihuaiyamrfz_prefix: "琳琅",
	spsongzangrenmrfz: "圣约送葬人",
	spsongzangrenmrfz_prefix: "圣约",
	spjiexikamrfz: "涤火杰西卡",
	spjiexikamrfz_prefix: "涤火",
	tifengmrfz: "提丰",
	spxiaoyangmrfz: "纯烬艾雅法拉",
	spxiaoyangmrfz_prefix: "纯烬",
	suxinmrfz: "塑心",
	hedeleimrfz: "赫德雷",
	zhisongmrfz: "止颂",
	weiweiannamrfz: "薇薇安娜",
	laiyimrfz: "莱伊",
	shumrfz: "黍",
	zuolemrfz: "左乐",
	jianmrfz: "锏",
	elamrfz: "艾拉",
	asikalunmrfz: "阿斯卡纶",
	luogesimrfz: "逻格斯",
	weishidaiermrfz: "维什戴尔",
	mowangmrfz: "魔王",
	wuerbianmrfz: "乌尔比安",
	nifumrfz:"妮芙",
	narentuyamrfz:"娜仁图亚",
	peipeimrfz:'佩佩',
	amiyamrfz: "阿米娅",
	spamiyamrfz: '近卫阿米娅',
	spamiyamrfz_prefix: {
		name:'近卫',
		layout:"amiya"
	},
	fulankamrfz: '芙兰卡',
	xingjimrfz: '星极',
	xingyuanmrfz: '星源',
	zhanchemrfz: '战车',
	shanjimrfz: '闪击',
	shuanghuamrfz: '霜华',
	bohuimrfz: '柏喙',
	baimianxiaomrfz: '白面鸮',
	cimeimrfz: '刺玫',
	hongmrfz: '红',
	dekesasimrfz: '德克萨斯',
	baijinmrfz: '白金',
	yintuoluomrfz: '因陀罗',
	wenmimrfz: '温米',
	meiermrfz: '梅尔',
	lindongmrfz: '凛冬',
	yunxingmrfz: '陨星',
	yumaobimrfz: '羽毛笔',
	ailisimrfz: '爱丽丝',
	tianhuomrfz: '天火',
	linguangmrfz: '临光',
	haimomrfz: '海沫',
	xiaomanmrfz: '小满',
	wanqingmrfz: '万顷',
	gelaokesimrfz: '格劳克斯',
	haidimrfz: '海蒂',
	yaxinmrfz: '崖心',
	chuxuemrfz: '初雪',
	shixiemrfz: '狮蝎',
	hongsunmrfz: '红隼',
	xiyinmrfz: '稀音',
	yemomrfz: '夜魔',
	jingzhemrfz: '惊蛰',
	longshelanmrfz: '龙舌兰',
	docmrfz: '医生',
	innamrfz: '双月',
	linshimrfz: '凛视',
	medical_amiyamrfz: '医疗阿米娅',
	medical_amiyamrfz_prefix: {
		name:'医疗',
		layout:"amiya"
	},
	spfenmrfz: '历阵锐枪芬',
	spfenmrfz_prefix: '历阵锐枪',
	hainimrfz:'海霓',
	shenxunmrfz:'深巡',
	mingjiaomrfz:'明椒',
	daifeienmrfz:'戴菲恩',
	xirenmrfz:'锡人',
	suocaomrfz:'莎草',
	maluxiermrfz: '玛露希尔',
	laiousimrfz: "莱欧斯",
	senximrfz: "森西",
	qierchakemrfz:"奇尔查克",
	kaiselinmrfz:"凯瑟琳",
	paxinghaomrfz:"爬行号",
	bobumrfz:"波卜",
	spweinamrfz: "维娜·维多利亚",
	spweinamrfz_ab:"维多利亚",
	splapulandemrfz:"荒芜拉普兰德",
	splapulandemrfz_prefix:"荒芜",
	rendongmrfz:"忍冬",
	shijunzhemrfz:"弑君者",
	yunjimrfz:"云迹",
	feilaimrfz:"菲莱",
	caidumrfz:"裁度",
	shuangwangmrfz:"特蕾西娅&特雷西斯",
	shuangwangmrfz_ab:"萨卡兹双王",
	spjicimrfz: "引星棘刺",
	spjicimrfz_prefix: "引星",
	tekenuomrfz:"特克诺",
	muouwuzhemrfz: "木偶舞者",
	guiyanmrfz:"瑰盐",
	xingzhumrfz:"行著",
	yumrfz:"余",
	zhuhuangmrfz:"烛煌",
	xunlanmrfz:"寻澜",
	yindelaiximrfz: "隐德莱希",
	nuoweiermrfz: "诺威尔",
	spfurongmrfz:"濯尘芙蓉",
	spfurongmrfz_prefix:"濯尘",
	keluxiermrfz:"可露希尔",
	anzhelamrfz:"安哲拉",
	shuidengxinmrfz: "水灯心",
	aibulanamrfz:"爱布拉娜",
	muqianmrfz: "钼铅",
	mon3trmrfz:"mon3tr",
	alannamrfz:"阿兰娜",
	chengfengmrfz:"骋风",
	lingyinmrfz:"聆音",
	spnengtianshimrfz:"新约能天使",
	spnengtianshimrfz_prefix:"新约",
	leimiuanmrfz:"蕾缪安",
	xinyangjiaobanjimrfz:"信仰搅拌机",
	dibimrfz:"蒂比",
	jiushenmrfz:"酒神",
	Christinemrfz:"Christine",
	spheijiaomrfz:"太刀侠火龙S黑角",
	spheijiaomrfz_ab:"太刀侠黑角",
	spheijiaomrfz_prefix:"太刀侠",
	yunqingpingmrfz:"云青萍",
	spjingzhemrfz:"司霆惊蛰",
	spjingzhemrfz_prefix:"司霆",
	dianhumrfz:"电弧",
	ziyeyaomrfz:"紫野遥",
	songtongmrfz:"松桐",
	jixingmrfz:"吉星",
	spxingxiongmrfz: "斩业星熊",
	spxingxiongmrfz_prefix: "斩业",
	landumrfz: "蓝毒",
	fengchuanxiangzimrfz: "丰川祥子",
	ruoyemumrfz:"若叶睦",
	youtiansiruomaimrfz:"祐天寺若麦",
	sanjiaochuhuamrfz:"三角初华",
	bafanhailingmrfz:"八幡海铃",
	fengwanmrfz:"风丸",
	fengwan_zhioumrfz:"纸偶",
	minermrfz:"矿工游击队",
	dongshimrfz:"冬时",
	zheyamrfz:"折桠",
	zhenyanmrfz:"真言",
	Lancet2mrfz:"Lancet-2",
	THRMEXmrfz:"THRM-EX",
	Castle3mrfz:"Castle-3",
	PhonoR0mrfz:"PhonoR-0",
	xierdamrfz:"希尔达",
	yelamrfz:"耶拉",
	spyinhuimrfz:"凛御银灰",
	spyinhuimrfz_prefix:"凛御",
	spchuxuemrfz:"圣聆初雪",
	spchuxuemrfz_prefix:"圣聆",
	spxingyuanmrfz:"溯光星源",
	spxingyuanmrfz_prefix:"溯光",
	hadiyamrfz:"哈蒂娅",
	xueliemrfz:"雪猎",
	xielvmrfz:"协律",
	nasitimrfz:"娜斯提",
	tiankonghemrfz:"天空盒",
	baidurenmrfz:"摆渡人",
	titimrfz:"缇缇",
	xiangshimrfz:"响石",
	sptiaoxiangshimrfz:"撷英调香师",
	sptiaoxiangshimrfz_prefix:"撷英",
	wangmrfz:"望",
}

export  default  characterName;
